microservices-1 finished without *
lasdolphin/microservices pull request #4
Opened 2018-01-16 10:51 UTC by lasdolphin

Завершил основное ДЗ 21.
В ходе выполнения столкнулся с тем что Puma в контейнерах  ui и comment падала пока не установил гем json для ui и comment и tzinfo-data для  comment.

2018-01-16 19:24 UTC, chromko requested changes
По ходу самой работы всё неплохо.
Прошу исправить замечания

2018-01-16 19:24 UTC, chromko commented on ui/build_info.txt
> +9f842ff
build_info лучше git-игнорить

2018-01-16 19:24 UTC, chromko commented on post-py/docker_build.sh
> +docker build -t $USER_NAME/post .
Cейчас есть рассинхрон переменных USERNAME и USER_NAME. Надо бы прийти к чему-то одному.
P.S. Это наша недоработка, но чтобы не было дальнейших проблем советую исправить

2018-01-16 19:24 UTC, chromko commented on post-py/build_info.txt
> +9f842ff
build_info лучше git-игнорить

2018-01-16 19:24 UTC, chromko commented on comment/build_info.txt
> +9f842ff
build_info лучше git-игнорить

2018-01-16 19:24 UTC, chromko commented on build_info.txt
> +9f842ff
build_info лучше git-игнорить

2018-01-17 09:19 UTC, lasdolphin commented on post-py/docker_build.sh
> +docker build -t $USER_NAME/post .
Замечания исправил.

2018-01-17 09:23 UTC, lasdolphin commented on build_info.txt
> +9f842ff
Замечания исправил.

2018-01-17 20:47 UTC, chromko commented
Изменения посмотрел. Все ок.

2018-01-17 20:47 UTC, chromko approved these changes

2018-01-18 09:19 UTC, merged